allowBuilds:
  'remix@https://codeload.github.com/remix-run/remix/tar.gz/f112ef1b9b0a19951c2676a65c9b3fa53d17c5dc#path:packages/remix': true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@oxlint/binding-android-arm-eabi@1.69.0'
  - '@oxlint/binding-android-arm64@1.69.0'
  - '@oxlint/binding-darwin-arm64@1.69.0'
  - '@oxlint/binding-darwin-x64@1.69.0'
  - '@oxlint/binding-freebsd-x64@1.69.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.69.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.69.0'
  - '@oxlint/binding-linux-arm64-gnu@1.69.0'
  - '@oxlint/binding-linux-arm64-musl@1.69.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.69.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.69.0'
  - '@oxlint/binding-linux-riscv64-musl@1.69.0'
  - '@oxlint/binding-linux-s390x-gnu@1.69.0'
  - '@oxlint/binding-linux-x64-gnu@1.69.0'
  - '@oxlint/binding-linux-x64-musl@1.69.0'
  - '@oxlint/binding-openharmony-arm64@1.69.0'
  - '@oxlint/binding-win32-arm64-msvc@1.69.0'
  - '@oxlint/binding-win32-ia32-msvc@1.69.0'
  - '@oxlint/binding-win32-x64-msvc@1.69.0'
  - '@oxlint/plugins@1.69.0'
  - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-linux-arm@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-linux-x64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview-win32-x64@7.0.0-dev.20260608.1'
  - '@typescript/native-preview@7.0.0-dev.20260608.1'
  - oxlint@1.69.0
  - '@ai-sdk/gateway@3.0.127'
  - ai@6.0.199
  - prettier@3.8.4
  - '@opencode-ai/plugin@1.17.3'
  - '@opencode-ai/sdk@1.17.3'
  - ecc-universal@2.0.0
